#pragma once
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <windows.h>
#include <tchar.h>
#include <TlHelp32.h>
#include <algorithm>
#include <dwmapi.h>
#include <d3d11.h>
#include <windowsx.h>